---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: edgecdnx-cache
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        values:
          chart: ingress-nginx
          chartVersion: 4.12.1
          chartRepository: https://kubernetes.github.io/ingress-nginx
          namespace: edgecdnx-cache
          caches: '{{ index .metadata.annotations "edgecdnx.com/caches" }}'
        selector:
          matchExpressions:
            - key: edgecdnx.com/caching
              operator: In
              values:
                - "true"
                - "yes"
  template:
    metadata:
      name: edgecdnx-cache-{{ .name }}
    spec:
      project: default
      sources:
        - chart: "{{ .values.chart }}"
          repoURL: "{{ .values.chartRepository }}"
          targetRevision: "{{ .values.chartVersion }}"
          helm:
            releaseName: edgecdnx-cache
            ignoreMissingValueFiles: true
            values: |
              controller:
                metrics:
                  enabled: true
                  serviceMonitor:
                    enabled: true
                    additionalLabels:
                      release: edgecdnx-monitoring
                allowSnippetAnnotations: true
                ingressClass: ssd
                ingressClassResource:
                  enabled: true
                  default: false
                  name: ssd
                  controllerValue: "edgecdnx.com/ssd"
                service:
                  enabled: true
                hostPort:
                  enabled: false
                kind: DaemonSet
                extraVolumes:
                {{- range $cache := (fromJson .values.caches) }}
                  - name: cache-{{ $cache.name }}
                    hostPath:
                      path: "{{ $cache.path }}"
                      type: DirectoryOrCreate
                {{- end }}
                extraVolumeMounts:
                {{- range $cache := (fromJson .values.caches) }}
                  - name: cache-{{ $cache.name }}
                    mountPath: "{{ $cache.path }}"
                {{- end }}
                extraInitContainers:
                  - name: init-cache-dirs
                    image: busybox:1.34
                    command: ["/bin/sh", "-c"]
                    args:
                    {{- range $cache := (fromJson .values.caches) }}
                      - "mkdir -p {{ $cache.path }} && chmod -R 777 {{ $cache.path }};"
                    {{- end }}
                    volumeMounts:
                    {{- range $cache := (fromJson .values.caches) }}
                      - name: cache-{{ $cache.name }}
                        mountPath: "{{ $cache.path }}"
                    {{- end }}
                config:
                  proxy-buffering: "on"
                  annotations-risk-level: "Critical"
                  http-snippet: |
                    {{- range $cache := (fromJson .values.caches) }}
                    # Cache configuration for {{ $cache.name }}
                    proxy_cache_path {{ $cache.path }} levels=1:2 keys_zone={{ $cache.name }}:100m inactive=10080m use_temp_path=off;
                    {{- end }}
                  log-format-upstream: |
                    {"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent" }
      destination:
        namespace: "{{ .values.namespace }}"
        server: "{{ .server }}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
      ignoreDifferences: []
