---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: edgecdnx-controller
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        values:
          chart: edgecdnx-controller
          chartVersion: 0.15.1
          chartRepository: https://edgecdn-x.github.io/helm-charts/
          namespace: edgecdnx-controller-system
          role: cache-controller
          webhooks: "false"
        selector:
          matchExpressions:
            - key: edgecdnx.com/caching
              operator: In
              values:
                - "true"
                - "yes"
    - clusters:
        values:
          chart: edgecdnx-controller
          chartVersion: 0.15.1
          chartRepository: https://edgecdn-x.github.io/helm-charts/
          namespace: edgecdnx-controller-system
          role: router
          webhooks: "false"
        selector:
          matchExpressions:
            - key: edgecdnx.com/routing
              operator: In
              values:
                - "true"
                - "yes"
    - clusters:
        values:
          chart: edgecdnx-controller
          chartVersion: 0.15.2-dev.2
          chartRepository: https://edgecdn-x.github.io/helm-charts/
          namespace: edgecdnx-controller-system
          role: controller
          targetNamespace: "edgecdnx"
          webhooks: "true"
        selector:
          matchExpressions:
            - key: edgecdnx.com/control
              operator: In
              values:
                - "true"
                - "yes"
  template:
    metadata:
      name: edgecdnx-{{ .values.role }}{{ if ne .name "in-cluster" }}-{{ .name }}{{ end }}
    spec:
      project: default
      sources:
        - chart: "{{ .values.chart }}"
          repoURL: "{{ .values.chartRepository }}"
          targetRevision: "{{ .values.chartVersion }}"
          helm:
            # TODO unify
            releaseName: edgecdnx-controller-caching
            ignoreMissingValueFiles: true
            valuesObject:
              image:
                tag: latest
                pullPolicy: Always
              role: "{{ .values.role }}"
              targetNamespace: '{{ .values.targetNamespace | default "edgecdnx" }}'
              webhook:
                enabled: "{{ .values.webhooks }}"
      destination:
        namespace: "{{ .values.namespace }}"
        server: "{{ .server }}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big controller.
      ignoreDifferences: []
