---
apiVersion: infrastructure.edgecdnx.com/v1alpha1
kind: Location
metadata:
  name: eu-tenant-a
  namespace: edgecdnx
  labels:
    edgecdnx.com/tenant: tenant-a
spec:
  fallbackLocations:
    - us-tenant-a
  geoLookup:
    attributes:
      geoip/continent/code:
        values:
          - value: EU
          - value: AF
        weight: 10000
  nodeGroups:
    - name: whios
      flavor: ""
      nodes:
        - name: node-1
          ipv4: 100.59.99.192
        - name: node-2
          ipv4: 100.63.40.118
---
apiVersion: infrastructure.edgecdnx.com/v1alpha1
kind: Location
metadata:
  name: us-tenant-a
  namespace: edgecdnx
  labels:
    edgecdnx.com/tenant: tenant-a
spec:
  fallbackLocations:
    - eu-tenant-a
  geoLookup:
    attributes:
      geoip/continent/code:
        values:
          - value: NA
          - value: SA
          - value: AN
          - value: OC
          - value: AS
        weight: 10000
  nodeGroups:
    - name: whios
      flavor: ""
      nodes:
        - name: node-1
          ipv4: 98.88.64.13
        - name: node-2
          ipv4: 98.88.229.31