---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fluentbit-analytics
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        values:
          role: caching
        selector:
          matchExpressions:
            - key: edgecdnx.com/caching
              operator: In
              values:
                - "true"
                - "yes"
  template:
    metadata:
      name: fluentbit-analytics-{{ .name }}
    spec:
      project: default
      sources:
        - chart: fluent-bit
          repoURL: https://fluent.github.io/helm-charts
          targetRevision: 0.54.0
          helm:
            releaseName: fluentbit-analytics
            valuesObject:
              testFramework:
                enabled: false
              serviceMonitor:
                enabled: true
                selector:
                  release: edgecdnx-monitoring
              extraVolumes:
                - name: fluentbit-tls
                  secret:
                    secretName: edgecdnx-tls-analytics-{{ .name }}-client
                - name: fluentbit-cache-logs
                  hostPath:
                    path: /var/cache/fluentbit
                    type: DirectoryOrCreate
              extraVolumeMounts:
                - name: fluentbit-cache-logs
                  mountPath: /var/cache/fluentbit
                - name: fluentbit-tls
                  mountPath: /fluentbit/tls
                  readOnly: true
              config:
                inputs: |
                  [INPUT]
                      Name tail
                      Path /var/log/pods/edgecdnx-cache_edgecdnx-cache-*/controller/*.log
                      multiline.parser docker, cri
                      db /var/cache/fluentbit/flb_positions.db
                      Tag raw.cache
                      Read_From_Head true
                      Mem_Buf_Limit 150MB
                customParsers: |
                  [PARSER]
                    Name        cache-json
                    Format      json
                    Time_Key    time
                    Time_Format %Y-%m-%dT%H:%M:%S%z
                filters: |
                  [FILTER]
                      Name       parser
                      Match      raw.cache
                      Key_Name   log
                      Parser     cache-json

                  [FILTER]
                      Name rewrite_tag
                      Match raw.cache
                      Rule $v ^([0-9]+)$ logs.$1.{{ .name }} false
                outputs: |
                  [OUTPUT]
                      Name forward
                      Match logs.*
                      Host analytics.{{ .metadata.annotations.basedomain }}
                      Port 24224
                      tls On
                      tls.verity On
                      tls.ca_file /fluentbit/tls/ca.crt
                      tls.crt_file /fluentbit/tls/tls.crt
                      tls.key_file /fluentbit/tls/tls.key
      destination:
        namespace: analytics
        name: "{{ .name }}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
      ignoreDifferences: []
