apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: analytics.demo.edgecdnx.com
  name: fluentbit-analytics-fluent-bit-lb
  namespace: analytics
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: forward
      port: 24224
      protocol: TCP
      targetPort: forward
  selector:
    app.kubernetes.io/instance: fluentbit-analytics
    app.kubernetes.io/name: fluent-bit
  sessionAffinity: None
  type: LoadBalancer
