---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fluentbit-analytics
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        values:
          role: caching
        selector:
          matchExpressions:
            - key: edgecdnx.com/caching
              operator: In
              values:
                - "true"
                - "yes"
  template:
    metadata:
      name: fluentbit-analytics-{{ .name }}
    spec:
      project: default
      sources:
        - chart: fluent-bit
          repoURL: https://fluent.github.io/helm-charts
          targetRevision: 0.54.0
          helm:
            releaseName: fluentbit-analytics
            valuesObject:
              testFamework:
                enabled: false
              serviceMonitor:
                enabled: true
                selector:
                  release: edgecdnx-monitoring
              config:
                # TOOD read from beginning
                inputs: |
                  [INPUT]
                      Name tail
                      Path /var/log/pods/edgecdnx-cache_edgecdnx-cache-*/controller/*.log
                      multiline.parser docker, cri
                      Tag raw.cache
                      Read_From_Head false
                      Mem_Buf_Limit 150MB

                customParsers: |
                  [PARSER]
                    Name        json
                    Format      json

                filters: |
                  [FILTER]
                      Name stdout
                      Match raw.cache

                  [FILTER]
                      Name       parser
                      Match      raw.cache
                      Key_Name   log
                      Parser     json

                  [FILTER]
                      Name rewrite_tag
                      Match raw.cache
                      Rule $log['v'] ^([0-9]+)$ logs.$1.{{ .name }} false
                outputs: |
                  [OUTPUT]
                      name stdout
                      Match logs.*
      destination:
        namespace: analytics
        name: "{{ .name }}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
      ignoreDifferences: []
