---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: analytics
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        values:
          role: control
        selector:
          matchExpressions:
            - key: edgecdnx.com/control
              operator: In
              values:
                - "true"
                - "yes"
  template:
    metadata:
      name: nats-analytics
    spec:
      project: default
      sources:
        - chart: vector
          repoURL: https://helm.vector.dev
          targetRevision: 0.47.0
          helm:
            releaseName: vector-receiver
            valuesObject:
              role: Stateless-Aggregator
              serviceHeadless:
                enabled: false
              service:
                type: LoadBalancer
                annotations:
                  external-dns.alpha.kubernetes.io/hostname: analytics.{{ metadata.annotations.basedomain }}
              readinessProbe:
                httpGet:
                  path: /health
                  port: api
              extraVolumes:
                - name: fluent-tls
                  secret:
                    secretName: edgecdnx-tls-analytics-node
              extraVolumeMounts: 
                - name: fluent-tls
                  mountPath: /vector/fluent/tls
                  readOnly: true
              customConfig:
                data_dir: /vector-data-dir
                api:
                  enabled: true
                  graphql: false
                  address: 0.0.0.0:8686
                  playground: false
                sources:
                  fluent:
                    type: fluent
                    address: 0.0.0.0:24224
                    mode: tcp
                    tls:
                      enabled: true
                      ca_file: /vector/fluent/tls/ca.crt
                      crt_file: /vector/fluent/tls/tls.crt
                      key_file: /vector/fluent/tls/tls.key
                      verify_certificate: true
                      verify_hostname: true
                sinks:
                  nats:
                    type: nats
                    inputs: [fluent]
                    encoding:
                      codec: json
                    subject: "{{`{{ .tag }}`}}"
                    url: nats://nats-analytics-headless:4222
                    jetstream:
                      enabled: true
        - chart: nats
          repoURL: https://nats-io.github.io/k8s/helm/charts/
          targetRevision: 2.12.1
          helm:
            releaseName: nats-analytics
            valuesObject:
              tlsCA:
                enabled: false
              config:
                nats:
                  tls:
                    enabled: false
                cluster:
                  enabled: true
                  tls:
                    enabled: false
                jetstream:
                  enabled: true
                  fileStore:
                    enabled: true
                    dir: /data
                    pvc:
                      enabled: true
                      size: 10Gi
                      storageClassName: "{{ metadata.annotations.default_sc }}"
      destination:
        namespace: analytics
        name: "{{ name }}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
      ignoreDifferences: []
