---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: analytics
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        values:
          role: control
        selector:
          matchExpressions:
            - key: edgecdnx.com/control
              operator: In
              values:
                - "true"
                - "yes"
  template:
    metadata:
      name: nats-analytics
    spec:
      project: default
      sources:
        - chart: resource-thrower
          repoURL: https://edgecdn-x.github.io/helm-charts
          targetRevision: 0.1.0
          helm:
            releaseName: fluentbit-analytics-svc
            values: |
              resources:
                - apiVersion: v1
                  kind: Service
                  metadata:
                    annotations:
                      external-dns.alpha.kubernetes.io/hostname: analytics.{{ .metadata.annotations.basedomain }}
                    name: fluentbit-analytics-fluent-bit-lb
                  spec:
                    allocateLoadBalancerNodePorts: true
                    externalTrafficPolicy: Cluster
                    internalTrafficPolicy: Cluster
                    ipFamilies:
                      - IPv4
                    ipFamilyPolicy: SingleStack
                    ports:
                      - name: forward
                        port: 24224
                        protocol: TCP
                        targetPort: forward
                    selector:
                      app.kubernetes.io/instance: fluentbit-analytics
                      app.kubernetes.io/name: fluent-bit
                    sessionAffinity: None
                    type: LoadBalancer
        - chart: vector
          repoURL: https://helm.vector.dev
          targetRevision: 0.47.0
          helm:
            releaseName: vector-receiver
            valuesObject:
              role: Stateless-Aggregator
              service:
                type: LoadBalancer
              customConfig:
                data_dir: /vector-data-dir
                api:
                  enabled: true
                  address: 127.0.0.1:8686
                  playground: false
                sources:
                  fluent:
                    type: fluent
                    address: 0.0.0.0:24224
                    mode: tcp
                sinks:
                  stdout:
                    type: console
                    inputs: [fluent]
                    encoding:
                      codec: json
        - chart: fluent-bit
          repoURL: https://fluent.github.io/helm-charts
          targetRevision: 0.54.0
          helm:
            releaseName: fluentbit-analytics
            valuesObject:
              logLevel: debug
              kind: Deployment
              testFramework:
                enabled: false
              extraPorts:
                - name: forward
                  containerPort: 24224
                  port: 24224
                  protocol: TCP
              serviceMonitor:
                enabled: true
                selector:
                  release: edgecdnx-monitoring
              config:
                inputs: |
                  [INPUT]
                      Name forward
                      Listen              0.0.0.0
                      Port                24224
                filters: |
                  [FILTER]
                      Name stdout
                      Match *
                outputs: |
                  [OUTPUT]
                      Name stdout
                      Match *
                  [OUTPUT]
                      Name nats
                      Match *
                      Host nats-analytics-headless
                      Port 4222
        - chart: nats
          repoURL: https://nats-io.github.io/k8s/helm/charts/
          targetRevision: 2.12.1
          helm:
            releaseName: nats-analytics
            valuesObject:
              tlsCA:
                enabled: false
              #   secretName: edgecdnx-root-ca-analytics
              # service:
              #   merge:
              #     metadata:
              #       annotations:
              #         external-dns.alpha.kubernetes.io/hostname: analytics.{{ metadata.annotations.basedomain }}
              #     spec:
              #       type: LoadBalancer
              config:
                nats:
                  tls:
                    enabled: false
                    # secretName: edgecdnx-tls-analytics-node
                    # merge:
                    #   verify: true
                cluster:
                  enabled: true
                  tls:
                    enabled: false
                    # secretName: edgecdnx-tls-analytics-node
                    # merge:
                    #   verify: true
                jetstream:
                  enabled: true
                  fileStore:
                    enabled: true
                    dir: /data
                    pvc:
                      enabled: true
                      size: 10Gi
                      storageClassName: "{{ metadata.annotations.default_sc }}"
      destination:
        namespace: analytics
        name: "{{ name }}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
      ignoreDifferences: []
