---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: authentik
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        values:
          role: control
        selector:
          matchExpressions:
            - key: edgecdnx.com/control
              operator: In
              values:
                - "true"
                - "yes"
  template:
    metadata:
      name: authentik
    spec:
      project: default
      sources:
        - repoURL: '{{ index .metadata.annotations "edgecdnx.com/gitops-override-repo"}}'
          targetRevision: '{{ index .metadata.annotations "edgecdnx.com/gitops-override-revision"}}'
          ref: overrides
        - chart: "authentik"
          repoURL: https://charts.goauthentik.io/
          targetRevision: 2026.2.0
          helm:
            releaseName: authentik
            ignoreMissingValueFiles: true
            valueFiles:
              - $overrides/{{ index .metadata.annotations "edgecdnx.com/gitops-override-basepath"}}/authentik.values.yaml
            valuesObject:
              global:
                env:
                  - name: AUTHENTIK_POSTGRESQL__HOST
                    valueFrom:
                      secretKeyRef:
                        name: authentikdb-cluster-app
                        key: host
                  - name: AUTHENTIK_POSTGRESQL__USER
                    valueFrom:
                      secretKeyRef:
                        name: authentikdb-cluster-app
                        key: username
                  - name: AUTHENTIK_POSTGRESQL__PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: authentikdb-cluster-app
                        key: password
                  - name: AUTHENTIK_POSTGRESQL__NAME
                    valueFrom:
                      secretKeyRef:
                        name: authentikdb-cluster-app
                        key: dbname
              authentik:
                existingSecret: authentik-secret
              postgresql:
                enabled: false
              server:
                ingress:
                  enabled: true
                  className: nginx
                  hosts:
                    - host: auth.{{ .metadata.annotations.basedomain }}
                      paths:
                        - path: /
                          pathType: ImplementationSpecific
                  annotations:
                    cert-manager.io/cluster-issuer: cert-manager-http
                  tls:
                    - hosts:
                        - auth.{{ .metadata.annotations.basedomain }}
                      secretName: authentik-cert-tls
        - chart: resource-thrower
          helm:
            releaseName: authentik-secret
            valuesObject:
              resources:
                - apiVersion: "secretgenerator.mittwald.de/v1alpha1"
                  kind: "StringSecret"
                  metadata:
                    name: authentik-secret
                  spec:
                    data: {}
                    fields:
                      - fieldName: "AUTHENTIK_SECRET_KEY"
                        length: "50"
          repoURL: https://edgecdn-x.github.io/helm-charts
          targetRevision: 0.1.0                      
      destination:
        namespace: edgecdnx-controller-system
        name: "{{ .name }}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
      ignoreDifferences: []
