---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: edgecdnx
spec:
  acme:
    email: tbo@tbotech.sk
    privateKeySecretRef:
      name: cert-manager-acc-key-edgecdnx
    server: https://acme-v02.api.letsencrypt.org./directory
    solvers:
    - http01:
        ingress:
          class: nginx