---
apiVersion: infrastructure.edgecdnx.com/v1alpha1
kind: Service
metadata:
  name: akldjgsofheiwu.democdn.edgecdnx.com
  namespace: argocd
  labels:
    type: static
spec:
  cache: ssd
  cacheKey:
    queryParams:
    - v
    - ver
    - version
  certificate: {}
  customer:
    id: 1
    name: tbotech
  domain: akldjgsofheiwu.democdn.edgecdnx.com
  name: akldjgsofheiwu.democdn.edgecdnx.com
  originType: static
  staticOrigins:
  - hostHeader: tbotech.sk
    port: 443
    scheme: Https
    upstream: tbotech.sk
---
apiVersion: infrastructure.edgecdnx.com/v1alpha1
kind: Service
metadata:
  name: akldjgsofheiwu.democdn.edgecdnx.com
  namespace: argocd
  labels:
    type: signed
spec:
  cache: ssd
  cacheKey:
    queryParams:
    - v
    - ver
    - version
  certificate: {}
  customer:
    id: 1
    name: tbotech
  domain: ae4aesee9cooqu.democdn.edgecdnx.com
  name: ae4aesee9cooqu.democdn.edgecdnx.com
  originType: static
  staticOrigins:
  - hostHeader: tbotech.sk
    port: 443
    scheme: Https
    upstream: tbotech.sk
  secureKeys:
  - name: tbotechkey1
    value: aipie8Kahwahth8ohmeiwugheejahsh2