---
apiVersion: infrastructure.edgecdnx.com/v1alpha1
kind: Zone
metadata:
  name: democdn.edgecdnx.com
  namespace: edgecdnx
  labels:
    project: admin
spec:
  zone: democdn.edgecdnx.com
  email: noc.democdn.edgecdnx.com.
