---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: edgecdnx-mon-cluster-certs
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        flatList: true
  template:
    metadata:
      name: edgecdnx-mon-certs
    spec:
      project: default
      sources:
        - chart: resource-thrower
          helm:
            releaseName: edgecdnx-mon-certs
            values: |
              resources:
              {{- toYaml . | nindent 14 }}
              - apiVersion: argoproj.io/v1alpha1
                kind: EventBus
                metadata:
                  name: default
                spec:
                  jetstream:
                    version: 2.12.1
                    replicas: 1
                    persistence: # optional
                        storageClassName: {{ .default_sc }}
                        accessMode: ReadWriteOnce
                        volumeSize: 1Gi
              {{- range $cluster := .clusters }}
                - apiVersion: cert-manager.io/v1
                  kind: Certificate
                  metadata:
                    name: edgecdnx-tls-monitoring-{{ $cluster.name }}-client
                    namespace: monitoring
                  spec:
                    secretName: edgecdnx-tls-monitoring-{{ $cluster.name }}-client
                    commonName: prometheus-{{ $cluster.name }}.{{ $cluster.metadata.annotations.basedomain }}
                    usages:
                      - client auth
                    issuerRef:
                      name: mon-tls-issuer
                      kind: Issuer
                      group: cert-manager.io
              {{- end }}
          repoURL: https://edgecdn-x.github.io/helm-charts
          targetRevision: 0.1.0
      destination:
        namespace: monitoring
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big controller.
      ignoreDifferences: []
