---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: edgecdnx-monitoring-remote
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: edgecdnx.com/caching
              operator: In
              values:
                - "true"
                - "yes"
    - clusters:
        selector:
          matchExpressions:
            - key: edgecdnx.com/routing
              operator: In
              values:
                - "true"
                - "yes"
  template:
    metadata:
      name: edgecdnx-monitoring-remote-{{ name }}
    spec:
      project: default
      sources:
        - chart: "kube-prometheus-stack"
          repoURL: "https://prometheus-community.github.io/helm-charts"
          targetRevision: 79.0.1
          helm:
            releaseName: edgecdnx-monitoring
            valuesObject:
              kubeApiServer:
                enabled: false
              kubeProxy:
                enabled: false
              alertmanager:
                enabled: false
              grafana:
                enabled: false
              prometheus:
                enabled: true
                ingress:
                  enabled: false
                agentMode: true
                prometheusSpec:
                  remoteWrite:
                    - url: "prometheus.{{ metadata.annotations.basedomain }}/api/v1/write"
      destination:
        namespace: monitoring
        name: "{{ name }}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
      ignoreDifferences: []
