---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: edgecdnx-monitoring
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        values:
          role: control
        selector:
          matchExpressions:
            - key: edgecdnx.com/control
              operator: In
              values:
                - "true"
                - "yes"
  template:
    metadata:
      name: edgecdnx-monitoring
    spec:
      project: default
      sources:
        - repoURL: '{{ index .metadata.annotations "edgecdnx.com/gitops-override-repo"}}'
          targetRevision: '{{ index .metadata.annotations "edgecdnx.com/gitops-override-revision"}}'
          ref: overrides
        - chart: "kube-prometheus-stack"
          repoURL: "https://prometheus-community.github.io/helm-charts"
          targetRevision: 79.0.1
          helm:
            releaseName: edgecdnx-monitoring
            ignoreMissingValueFiles: true
            valueFiles:
              - $overrides/{{ index .metadata.annotations "edgecdnx.com/gitops-override-basepath"}}/monitoring.values.yaml
            valuesObject:
              kubeApiServer:
                enabled: false
              kubeProxy:
                enabled: false
              alertmanager:
                enabled: true
              grafana:
                envValueFrom:
                  ANALYTICS_DB_PASSWORD:
                    secretKeyRef:
                      name: timescaledb-cluster-app
                      key: password
                additionalDataSources:
                  - name: timescaledb
                    uid: analytics-timescaledb
                    type: postgres
                    url: timescaledb-cluster-rw:5432
                    user: app
                    jsonData:
                      timescaledb: true
                      database: app
                    secureJsonData:
                      password: $ANALYTICS_DB_PASSWORD
                    isDefault: false
                enabled: true
                ingress:
                  enabled: true
                  ingressClassName: nginx
                  annotations:
                    cert-manager.io/cluster-issuer: cert-manager-http
                  hosts:
                    - "grafana.{{ .metadata.annotations.basedomain }}"
                  tls:
                    - hosts:
                        - "grafana.{{ .metadata.annotations.basedomain }}"
                      secretName: grafana-cert-tls
                sidecar:
                  dashboards:
                    multicluster:
                      global:
                        enabled: true
              prometheus:
                enabled: true
                ingress:
                  enabled: true
                  ingressClassName: nginx
                  annotations:
                    cert-manager.io/issuer: mon-tls-issuer
                    cert-manager.io/subject-organizations: "EdgeCDNX"
                    cert-manager.io/subject-countries: "SK"
                    cert-manager.io/usages: "digital signature,key encipherment,server auth,client auth"
                    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
                    nginx.ingress.kubernetes.io/auth-tls-secret: monitoring/edgecdnx-root-ca-monitoring
                    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
                    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
                  hosts:
                  - "prometheus.{{ .metadata.annotations.basedomain }}"
                  tls:
                  - hosts:
                    - "prometheus.{{ .metadata.annotations.basedomain }}"
                    secretName: prometheus-cert-tls
                prometheusSpec:
                  enableRemoteWriteReceiver: true
                  enableFeatures: 
                    - metadata-wal-records
                  scrapeClasses:
                    - default: true
                      name: local-cluster
                      relabelings:
                        - targetLabel: cluster
                          replacement: "{{ .name }}"
                          action: replace
                        - targetLabel: role
                          replacement: "{{ .values.role }}"
                          action: replace
      destination:
        namespace: monitoring
        name: "{{ .name }}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences: []
